### PR TITLE
[WIP] hypothetical_improvement not to be merged

### LINKED ISSUE #19: slowdown of qtpy GUI over extended time
QtPy GUI slows down CPU over time, which may cause data collection errors and frustrate users.

### PR DESCRIPTION
**Pull request by kameyer226**
The above may close #19  if properly done, this is a suggestion to improve the quality of timing of updates of qtpy.  Best tested on a fake system properly emulating the actual systems using it.

Class inheritance validation has not been performed for the new variables yet.   This is a hypothesis.

### CODE REVIEW

**Comment by ksunden** [comment]
I doubt this is the problem (or at least not the only problem), as it has been shown that the memory leak exists even when no main window has been opened.

**Comment by kameyer226** [comment]
It's lines 92-94 in `_toggle_hide` that concerns me the most...it looks like it keeps writing and writing when it doesn't need to be.

**Comment by ksunden** [comment]
Those lines are only ever called in response to user interaction, so not as if it is constantly running. Also because there is a symmetric difference operation, the new set will _always_ be different than the existing set, so the check is not needed.

Symmetric difference will add an element if it is not in the set and remove it if it is in the set, thus the resultant set cannot be the same as the input set.

**Comment by kameyer226** [comment]
"even when no main window has been opened"  is that the advanced menu or the entire qtpy GUI?

**Comment by ksunden** [comment]
that is the advanced widget, which is referred to in the code as "main widget"

(I always mix them up because the code does refer to main window as the overall application window, but here I actually mean main widget)

**Comment by kameyer226** [comment]
Doesn't `widget.hide()` in `_show_main_widget` imply that it is processing updates to the widget even though it is hidden?

**Comment by ksunden** [comment]
There is no practical difference in terms of memory usage or more than momentary CPU usage in response to user input which should be imperceptible and short lived to any of the code here.

We cap the number of main widgets held in memory to 3, but all 3 are indeed being updated even when hidden, such that you can flip back and forth between a couple of advanced widgets without it having to completely recreate (and forgetting the history of points collected).

That is intended behavior. And it is not in and of itself causing the problem we are seeing, as far as I can tell. Since, as I stated, the problem exists even when none of them have been opened and thus the lines of code touched here have not been run at all.

**Comment by kameyer226** [comment]
can you remove Splash and test for leaks that way, or will that completely break the code?

**Comment by ksunden** [comment]
It is highly probable that the leak is occurring relating to the left hand sidebar and/or background tasks communicating with the daemons themselves. the point that I think that it is not related to the main widgets is not in any way supposed to indicate that I thought it was the splash screen, that is highly improbable and spending time disabling that is almost certainly a fruitless endeavor.

**Comment by kameyer226** [comment]
`()

     def _add_card(self, key, name):
        tree = self._root_item
        if key in self.hidden:
            tree = self._hidden
        try:
            host, port = key.split(":")
            port = int(port)
            qclient = QClient(host=host, port=port)
            self._qclients[key] = qclient
            pos = calc_position(tree, qclient.id()["name"])
            card = qtype_items.append_card_item(qclient, tree, pos)
            view_advanced = tree[pos][-1]
            if view_advanced.get()["label"] != "":
                view_advanced = tree[pos][-2]
            view_advanced.updated_connect(
                lambda _: functools.partial(self._show_main_widget, key=key)()
            )
            view_advanced.append(
                qtypes.Button("", text="Unhide" if tree == self._hidden else "Hide")
            )
            view_advanced[-1].updated_connect(
                lambda _: functools.partial(
                    self._toggle_hide, key=key, label=card.get()["label"]
                )()
            )

        except Exception as e:
            card = qtypes.String(name, disabled=True)
            pos = calc_position(tree, name)
            tree.insert(pos, card)
            tree[pos].set_value("offline")
            tree[pos].append(qtypes.Button("", text="Unhide" if tree == self._hidden else "Hide"))
            tree[pos][-1].updated_connect(
                functools.partial(self._toggle_hide, key=key, label=card.get()["label"])
            ) 
 `

Is it possible that this `try except` statement is creating a leak because the Exception handler doesn't necessarily free up the qclient memory when it is thrown?   Maybe our fake system can be used to test potential fixes here. @ddkohler  @ksunden

**Comment by ksunden** [comment]
Again, I have my doubts based on the fact that this code is only called in response to direct user interaction, and I have seen the leak occur with no user interaction.

**Comment by ddkohler** [comment]
@kameyer226 I am not very familiar with issue #19, so I don't have much input.  It would be great to remove memory build-ups, but this isn't high on my priority list, since 
* there is a workable solution (restart qtpy/only open qtpy when needed)
* qtpy is not needed for acquisitions
* it seems like troubleshooting might be time consuming

(please correct me if you think it is high priority)

I don't know when I will get to this myself, but I would welcome you to experiment if you think it's worthwhile.

**Comment by kameyer226** [comment]
If pyQt is responsible for a memory leak, it may be a specific widget causing the leak.  With qtpy troubleshooting now reduced to about 3 dozen lines of code, I wanted to see if it could be pinpointed to see whether a bad widget was being used in cmds as well and responsible for problems there.

**Pull request closed without merging**
